# Generated by Django 5.0.2 on 2024-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_rename_place_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_pesentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
